version: '2'
services:
  master:
    image: lixiepeng/lxp:tweet
    command: /bin/bash ./run.sh
    environment:
      SCRIPT: master_test.py
    labels: 
      io.rancher.scheduler.affinity:host_label: deploy=deploy
      io.rancher.container.pull_image: always

  deploy1:
    image: lixiepeng/lxp:tweet
    command: /bin/bash ./run.sh
    environment:
      SCRIPT: worker_test.py
      MONGOHOST: localhost
      REDISHOST: localhost
    labels:
      io.rancher.scheduler.affinity:host_label: deploy=deploy
      io.rancher.container.pull_image: always
  
  deploy2:
    image: lixiepeng/lxp:tweet
    command: /bin/bash ./run.sh
    environment:
      SCRIPT: worker_test.py
      MONGOHOST: localhost
      REDISHOST: localhost
    labels:
      io.rancher.scheduler.affinity:host_label: deploy=deploy
      io.rancher.container.pull_image: always