version: '2'
services:
  master:
    image: lixiepeng/lxp:tweet
    command: git pull && python ./spider/master.py
    labels:
      io.rancher.scheduler.affinity: spider.master:true

  worker:
    image: lixiepeng/lxp:tweet
    command: git pull && python ./spider/worker.py
    labels:
      io.rancher.scheduler.affinity: spider:true